const LAST_DATA_STORAGE_KEY = "lastExtractionData";
const UI_STATE_STORAGE_KEY = "lastPopupUiState";
const BOOKMARKS_STORAGE_KEY = "routerBookmarks";
const ROUTER_MODEL_STORAGE_KEY = "detectedRouterModel";
const PENDING_AUTH_ERROR_STORAGE_KEY = "pendingAuthErrorMessage";
const MAX_BOOKMARK_CREDENTIALS = 6;

export {
  LAST_DATA_STORAGE_KEY,
  UI_STATE_STORAGE_KEY,
  BOOKMARKS_STORAGE_KEY,
  ROUTER_MODEL_STORAGE_KEY,
  PENDING_AUTH_ERROR_STORAGE_KEY,
  MAX_BOOKMARK_CREDENTIALS,
};
